"""Board Quality and Placement Predictor Network (Value Oracle).

Predicts expected final placement (1.0 to 8.0) and Top-4 probability from board
state representations generated by the Multi-Modal Fusion Trunk.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from tft_ai_player.embeddings.model import MultiModalFusionTrunk
from tft_ai_player.simulation.config import SetData
from tft_ai_player.simulation.models import Player


class BoardQualityNet(nn.Module):
    """Deep Neural Board Evaluator and Tournament Placement Oracle.

    Maps (board units, items, traits, stage, economy) -> E[Placement] ∈ [1.0, 8.0]
    and P(Top-4) ∈ [0.0, 1.0].
    """

    def __init__(
        self,
        trunk: MultiModalFusionTrunk,
        freeze_trunk: bool = True,
        hidden_dim: int = 128,
        dropout: float = 0.1,
    ) -> None:
        super().__init__()
        self.trunk = trunk
        self.freeze_trunk = freeze_trunk

        if freeze_trunk:
            for p in self.trunk.parameters():
                p.requires_grad = False

        f_dim = self.trunk.fused_dim  # typically 320D
        scalar_dim = 8  # Direct uncompressed scalars: [HP, Gold, Level, Streak, Stage, Round, Unit Count, Item Count]
        in_features = f_dim + scalar_dim

        # 1. Placement Regression Head: E[Placement] ∈ [1.0, 8.0]
        self.placement_head = nn.Sequential(
            nn.Linear(in_features, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.GELU(),
            nn.Linear(hidden_dim // 2, 1),
        )

        # 2. Top-4 Classification Head: Binary Cross-Entropy / Logits
        self.top4_head = nn.Sequential(
            nn.Linear(in_features, hidden_dim // 2),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim // 2, 2),
        )

    def forward(
        self,
        board_champ_ids: torch.Tensor,
        board_star_levels: torch.Tensor | None = None,
        board_item_ids: torch.Tensor | None = None,
        board_traits: torch.Tensor | None = None,
        state_scalars: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Compute placement prediction and Top-4 classification logits.

        Combines the deep board representation from the Multi-Modal Trunk with
        direct, uncompressed skip-connections of the focal player's current health,
        gold, stage, and level.

        Returns:
            tuple[torch.Tensor, torch.Tensor]:
                - placement_pred: (B, 1) expected placement in [1.0, 8.0]
                - top4_logits: (B, 2) unnormalized logits for [Not Top-4, Top-4]
        """
        board_feat = self.trunk.encode_board(
            board_champ_ids=board_champ_ids,
            board_star_levels=board_star_levels,
            board_item_ids=board_item_ids,
            board_traits=board_traits,
        )

        if state_scalars is not None:
            state_feat = self.trunk.state_mlp(state_scalars)
            scalars_direct = state_scalars
        else:
            state_feat = torch.zeros(
                board_feat.shape[0], self.trunk.state_feat_dim, device=board_feat.device
            )
            scalars_direct = torch.zeros(board_feat.shape[0], 8, device=board_feat.device)

        fused = self.trunk.fusion(torch.cat([board_feat, state_feat], dim=-1))

        # Direct skip-connection: fused representation + raw focal state scalars
        combined = torch.cat([fused, scalars_direct], dim=-1)

        raw_place = self.placement_head(combined)
        # Bounded between 1.0 (1st place) and 8.0 (8th place)
        placement_pred = 1.0 + 7.0 * torch.sigmoid(raw_place)

        top4_logits = self.top4_head(combined)

        return placement_pred, top4_logits

    @torch.no_grad()
    def evaluate_board_tensors(
        self,
        board_champ_ids: torch.Tensor,
        board_star_levels: torch.Tensor | None = None,
        board_item_ids: torch.Tensor | None = None,
        board_traits: torch.Tensor | None = None,
        state_scalars: torch.Tensor | None = None,
    ) -> tuple[float, float, float]:
        """Evaluate a single board state and return scalar quality metrics.

        Returns:
            tuple[float, float, float]:
                - quality_score: Scalar in [0.0, 10.0] (higher is better)
                - expected_placement: Float in [1.0, 8.0] (lower is better)
                - top4_probability: Float in [0.0, 1.0] (higher is better)
        """
        self.eval()
        if board_champ_ids.dim() == 1:
            board_champ_ids = board_champ_ids.unsqueeze(0)
        if board_star_levels is not None and board_star_levels.dim() == 1:
            board_star_levels = board_star_levels.unsqueeze(0)
        if board_item_ids is not None and board_item_ids.dim() == 2:
            board_item_ids = board_item_ids.unsqueeze(0)
        if board_traits is not None and board_traits.dim() == 1:
            board_traits = board_traits.unsqueeze(0)
        if state_scalars is not None and state_scalars.dim() == 1:
            state_scalars = state_scalars.unsqueeze(0)

        placement_pred, top4_logits = self.forward(
            board_champ_ids=board_champ_ids,
            board_star_levels=board_star_levels,
            board_item_ids=board_item_ids,
            board_traits=board_traits,
            state_scalars=state_scalars,
        )

        exp_place = float(placement_pred.item())
        top4_probs = F.softmax(top4_logits, dim=-1)
        top4_prob = float(top4_probs[0, 1].item())

        # Quality score: 8.0 - placement + 2 * top4_prob -> ranges ~[0.0, 9.0]
        quality_score = (8.0 - exp_place) + (2.0 * top4_prob)
        return quality_score, exp_place, top4_prob

    def save_checkpoint(self, path: str | Path) -> None:
        """Serialize model weights and architecture configuration."""
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        torch.save(
            {
                "model_state_dict": self.state_dict(),
                "trunk_config": {
                    "num_champs": self.trunk.num_champs,
                    "num_items": self.trunk.num_items,
                    "num_traits": self.trunk.num_traits,
                    "fused_dim": self.trunk.fused_dim,
                },
            },
            p,
        )

    @classmethod
    def load_checkpoint(
        cls,
        path: str | Path,
        trunk: MultiModalFusionTrunk | None = None,
        device: torch.device | None = None,
    ) -> BoardQualityNet:
        """Load trained BoardQualityNet from disk."""
        target_device = device or torch.device("cpu")
        checkpoint = torch.load(path, map_location=target_device, weights_only=False)
        if trunk is None:
            cfg = checkpoint.get("trunk_config", {})
            trunk = MultiModalFusionTrunk(
                num_champs=cfg.get("num_champs", 500),
                num_items=cfg.get("num_items", 300),
                num_traits=cfg.get("num_traits", 60),
                fused_dim=cfg.get("fused_dim", 320),
            )
        model = cls(trunk=trunk, freeze_trunk=True)
        model.load_state_dict(checkpoint.get("model_state_dict", checkpoint), strict=False)
        model.to(target_device)
        model.eval()
        return model
