"""Set 18 'Enchanted Wilds' Augment Definitions and Catalog."""

from __future__ import annotations

from tft_ai_player.simulation.augments import (
    AugmentCategory,
    AugmentDef,
    AugmentTier,
)

SET18_AUGMENTS_CATALOG: dict[str, AugmentDef] = {
    # --- SILVER TIER (Tier 1) ---
    "DA_18_OnesTwosThree": AugmentDef(
        augment_id="DA_18_OnesTwosThree",
        name="Ones Two Three",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.ECONOMY,
        description="Gain 3 1-cost champions, 2 2-cost champions, and 1 3-cost champion.",
        instant_champions=(("TFT18_Akali", 1), ("TFT18_Camille", 1), ("TFT18_Varus", 1), ("TFT18_Alistar", 1), ("TFT18_Warwick", 1), ("TFT18_MasterYi", 1)),
    ),
    "DA_18_GoodForSomethingI": AugmentDef(
        augment_id="DA_18_GoodForSomethingI",
        name="Good For Something I",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.ECONOMY,
        description="Champions without items have a chance to drop gold on combat victory.",
        gold_per_round=1,
    ),
    "DA_18_BranchingOut": AugmentDef(
        augment_id="DA_18_BranchingOut",
        name="Branching Out",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.ITEM,
        description="Gain a random Emblem.",
        instant_items=("TFT17_Item_AstronautEmblemItem",),
    ),
    "DA_18_ComponentGrabBag": AugmentDef(
        augment_id="DA_18_ComponentGrabBag",
        name="Component Buffet",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.ITEM,
        description="Gain 1 random component and 2 gold.",
        instant_gold=2,
        instant_components=1,
    ),
    "DA_18_SilverSpoon": AugmentDef(
        augment_id="DA_18_SilverSpoon",
        name="Silver Spoon",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.LEVEL_XP,
        description="Gain 10 XP immediately.",
        instant_xp=10,
    ),
    "DA_18_Recombobulator": AugmentDef(
        augment_id="DA_18_Recombobulator",
        name="Recombobulator",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.SHOP_REROLL,
        description="Gain 1 Magnetic Remover and 2 Reforgers.",
        instant_removers=1,
        instant_reforgers=2,
    ),
    "DA_18_PandorasBench": AugmentDef(
        augment_id="DA_18_PandorasBench",
        name="Pandora's Bench",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.SHOP_REROLL,
        description="Gain 2 gold. At the start of every round, champions on the 3 rightmost bench slots transform into random champions of the same cost.",
        instant_gold=2,
    ),
    "DA_18_AFK": AugmentDef(
        augment_id="DA_18_AFK",
        name="AFK",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.ECONOMY,
        description="You cannot perform actions for the next 3 rounds. Afterwards, gain 18 gold.",
        instant_gold=18,
    ),
    "DA_18_CareTakerAlly": AugmentDef(
        augment_id="DA_18_CareTakerAlly",
        name="Caretaker's Ally",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.ECONOMY,
        description="Gain a random 2-cost champion now. Gain another copy each time you level up.",
        instant_champions=(("TFT18_Warwick", 1),),
    ),
    "DA_18_ItemGrabBagI": AugmentDef(
        augment_id="DA_18_ItemGrabBagI",
        name="Item Grab Bag I",
        tier=AugmentTier.SILVER,
        category=AugmentCategory.ITEM,
        description="Gain 1 random completed item and 1 Reforger.",
        instant_items=("TFT_Item_GuinsoosRageblade",),
        instant_reforgers=1,
    ),

    # --- GOLD TIER (Tier 2) ---
    "DA_18_BigGrabBag": AugmentDef(
        augment_id="DA_18_BigGrabBag",
        name="Big Grab Bag",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.ITEM,
        description="Gain 3 random components, 2 gold, and 1 Reforger.",
        instant_gold=2,
        instant_components=3,
        instant_reforgers=1,
    ),
    "DA_18_BranchingOutPlus": AugmentDef(
        augment_id="DA_18_BranchingOutPlus",
        name="Branching Out+",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.ITEM,
        description="Gain a random Emblem and a Reforger.",
        instant_items=("TFT17_Item_DarkStarEmblemItem",),
        instant_reforgers=1,
    ),
    "DA_18_BlossomTraitAugment": AugmentDef(
        augment_id="DA_18_BlossomTraitAugment",
        name="Blossom's Call",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.TRAIT_EMBLEM,
        description="When you buy a Wisp, gain a random Blossom champion. Gain a Yunara, a Yorick, and a Karma.",
        instant_champions=(("TFT18_Yunara", 1), ("TFT18_Karma", 1)),
        associated_traits=("Blossom",),
    ),
    "DA_18_CovenTraitAugment_LootToAP": AugmentDef(
        augment_id="DA_18_CovenTraitAugment_LootToAP",
        name="Dark Ritual",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.TRAIT_EMBLEM,
        description="Converting Coven Essence grants bonus AP and cash. Gain a Camille and an Elise.",
        instant_champions=(("TFT18_Camille", 1), ("TFT18_Elise", 1)),
        associated_traits=("Coven",),
    ),
    "DA_18_FOURcing": AugmentDef(
        augment_id="DA_18_FOURcing",
        name="FOURcing",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.ECONOMY,
        description="Gain a random 4-cost champion immediately.",
        instant_champions=(("TFT18_Ahri", 1),),
    ),
    "DA_18_FloraFatalisAugment": AugmentDef(
        augment_id="DA_18_FloraFatalisAugment",
        name="Consuming Flora",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.TRAIT_EMBLEM,
        description="Gain a Flora Fatalis emblem and 3 gold.",
        instant_gold=3,
        instant_items=("TFT17_Item_PrimordianEmblemItem",),
        associated_traits=("Flora Fatalis",),
    ),
    "DA_18_RichGetRicher": AugmentDef(
        augment_id="DA_18_RichGetRicher",
        name="Rich Get Richer",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.ECONOMY,
        description="Gain 12 gold. Your maximum interest is increased to 7.",
        instant_gold=12,
        max_interest_cap=7,
    ),
    "DA_18_RichGetRicherPlus": AugmentDef(
        augment_id="DA_18_RichGetRicherPlus",
        name="Rich Get Richer+",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.ECONOMY,
        description="Gain 18 gold. Your maximum interest is increased to 7.",
        instant_gold=18,
        max_interest_cap=7,
    ),
    "DA_18_TradeSector": AugmentDef(
        augment_id="DA_18_TradeSector",
        name="Trade Sector",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.SHOP_REROLL,
        description="Gain a free shop refresh every round. Gain 2 gold.",
        instant_gold=2,
        free_rerolls_per_round=1,
    ),
    "DA_18_ClearMind": AugmentDef(
        augment_id="DA_18_ClearMind",
        name="Clear Mind",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.LEVEL_XP,
        description="If you have no champions on your bench at the end of a round, gain 3 XP.",
        xp_per_round=3,
    ),
    "DA_18_ClutteredMind": AugmentDef(
        augment_id="DA_18_ClutteredMind",
        name="Cluttered Mind",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.LEVEL_XP,
        description="If your bench is full at the end of a round, gain 3 XP. Gain 4 1-cost champions.",
        instant_champions=(("TFT18_Akali", 1), ("TFT18_Camille", 1), ("TFT18_Karma", 1), ("TFT18_Varus", 1)),
        xp_per_round=3,
    ),
    "DA_18_PatientStudy": AugmentDef(
        augment_id="DA_18_PatientStudy",
        name="Patient Study",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.LEVEL_XP,
        description="After player combat, gain 2 XP if you won or 3 XP if you lost.",
        xp_per_round=2,
    ),
    "DA_18_Slammin": AugmentDef(
        augment_id="DA_18_Slammin",
        name="Slammin'",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.LEVEL_XP,
        description="If you have no items on your bench at the end of player combat, gain 2 XP. Gain 1 completed item.",
        instant_items=("TFT_Item_InfinityEdge",),
        xp_per_round=2,
    ),
    "DA_18_HeroicGrabBag": AugmentDef(
        augment_id="DA_18_HeroicGrabBag",
        name="Heroic Grab Bag",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.ITEM,
        description="Gain 2 Champion Duplicators and 4 gold.",
        instant_gold=4,
        instant_duplicators=2,
    ),
    "DA_18_LastStand": AugmentDef(
        augment_id="DA_18_LastStand",
        name="Last Stand",
        tier=AugmentTier.GOLD,
        category=AugmentCategory.COMBAT,
        description="The first time you would be eliminated or drop below 1 Health, instead gain massive combat stats.",
    ),

    # --- PRISMATIC TIER (Tier 3) ---
    "DA_18_DuoQueue": AugmentDef(
        augment_id="DA_18_DuoQueue",
        name="Duo Queue",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.ECONOMY,
        description="Gain 2 random 5-cost champions and 2 copies of a random component.",
        instant_champions=(("TFT18_Alune", 1), ("TFT18_Draven", 1)),
        instant_components=2,
    ),
    "DA_18_OneTwoFive": AugmentDef(
        augment_id="DA_18_OneTwoFive",
        name="One, Two, Five!",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.ECONOMY,
        description="Gain 1 random component, 2 gold, and 1 random 5-cost champion.",
        instant_gold=2,
        instant_components=1,
        instant_champions=(("TFT18_Ashe", 1),),
    ),
    "DA_18_LuxAugmentII": AugmentDef(
        augment_id="DA_18_LuxAugmentII",
        name="Master of All Origins",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.TRAIT_EMBLEM,
        description="Gain a Lux and a Spear of Shojin. Lux provides +2 to her chosen trait.",
        instant_champions=(("TFT18_Lux", 1),),
        instant_items=("TFT_Item_SpearOfShojin",),
        associated_traits=("Avatar", "Spellweaver"),
    ),
    "DA_18_LevelUp": AugmentDef(
        augment_id="DA_18_LevelUp",
        name="Level Up!",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.LEVEL_XP,
        description="When you buy experience points, gain an additional 3 XP. Gain 12 XP immediately.",
        instant_xp=12,
    ),
    "DA_18_HedgeFund": AugmentDef(
        augment_id="DA_18_HedgeFund",
        name="Hedge Fund",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.ECONOMY,
        description="Gain 22 gold. Your maximum interest is increased to 10.",
        instant_gold=22,
        max_interest_cap=10,
    ),
    "DA_18_NewRecruit": AugmentDef(
        augment_id="DA_18_NewRecruit",
        name="New Recruit",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.TEAM_SIZE,
        description="Gain +1 maximum team size and a Champion Duplicator.",
        instant_team_size=1,
        instant_duplicators=1,
    ),
    "DA_18_CursedCrown": AugmentDef(
        augment_id="DA_18_CursedCrown",
        name="Cursed Crown",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.TEAM_SIZE,
        description="Gain +2 maximum team size, but you take 100% increased player damage on losses.",
        instant_team_size=2,
    ),
    "DA_18_PrismaticTicket": AugmentDef(
        augment_id="DA_18_PrismaticTicket",
        name="Prismatic Ticket",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.SHOP_REROLL,
        description="Each time your shop is refreshed, you have a 50% chance to gain a free refresh.",
        free_rerolls_per_round=2,
    ),
    "DA_18_RadiantRelics": AugmentDef(
        augment_id="DA_18_RadiantRelics",
        name="Radiant Relics",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.ITEM,
        description="Gain 1 Radiant Item and 1 Magnetic Remover.",
        instant_items=("TFT_Item_GuinsoosRageblade",),
        instant_removers=1,
    ),
    "DA_18_GoingLong": AugmentDef(
        augment_id="DA_18_GoingLong",
        name="Going Long",
        tier=AugmentTier.PRISMATIC,
        category=AugmentCategory.ECONOMY,
        description="You no longer gain interest. At the start of each round, gain 4 XP and 4 gold.",
        max_interest_cap=0,
        xp_per_round=4,
        gold_per_round=4,
    ),
}
